<?php
use Lib\Router;
?>
<h2>Добавить города в базу</h2>

<div>
    <?= isset($args['msg'])?$args['msg']:null?>
    <form action="" method="post">
        <input class="form-control admin-form-about" type="text" name="cities_source" placeholder="Введите URL XML файла"><br>
        <input class="btn btn-success" type="submit" name="submit" value="Загрузить">
        <a href="<?= Router::getRoute('admin', 'adm_default') ?>" class="btn btn-danger">Отмена</a>
    </form>
</div>