<?php
use Lib\Router;
use Lib\Session;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?= $args['page_title']; ?></title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="/View/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/View/bootstrap/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/View/bootstrap/css/slider.css">
    <link rel="stylesheet" href="/View/bootstrap/css/media.css">
    <script src="/View/js/jquery-1.11.0.js"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<?php if( Session::get('user') && $_SESSION['user']['access'] >= 4 ){ ?>
    <div class="container">
        <!-- Static navbar -->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="">Админка</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?=Router::getRoute('admin', 'adm_default');?>">Главная</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?=Router::getRoute('admin', 'adm_logout');?>">Выход</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>
    </div> <!-- /container -->
    <div class="container">
        <?php echo $data; ?>
    </div><!-- /.container -->
<?php } else { ?>
    <div class="container">
        <div class="row">
            <div class="col-md-11 col-xs-5 col-sm-8">
                <div class="auth_container">
                    <h3>Авторизация</h3>
                    <span class="c_form_err_txt"><?php echo Session::getFlash(); ?></span>
                    <div class="form form_border">
                        <form action="" method="post">
                            <p>Логин</p>
                            <input type="text" name="login" placeholder="">
                            <span class="c_form_err_txt"><?php echo isset($args['errors']['login'])?$args['errors']['login']:null; ?></span>

                            <p>Пароль</p>
                            <input type="password" name="password" placeholder="">
                            <span class="c_form_err_txt"><?php echo isset($args['errors']['password'])?$args['errors']['password']:null; ?></span><br><br>
                            <input class="contact_button" type="submit" value="Войти">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<!-- Bootstrap core JavaScript

<!-- Placed at the end of the document so the pages load faster -->
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>
