<?php
use Lib\Router;
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title><?= $args['page_title']; ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="View/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="View/bootstrap/css/main.css">
    <link rel="stylesheet" href="View/Css/style.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <header >
        <div id="bgndVideo" class="player"
             data-property="{
		videoURL:'https://www.youtube.com/watch?v=qREKP9oijW',
		containment:'header',
		autoPlay:true,
		mute:true,
		startAt:0,
		opacity:1,
		showControls : false
		}">
        </div>
        <div class="bg_container">
            <div class="containers">
                <?= $data; ?>
            </div>
        </div>
    </header>


    <script src="View/bootstrap/js/jquery-1.11.1.min.js"></script>
    <script src="View/bootstrap/js/jquery.mb.YTPlayer.js"></script>
    <script src="View/bootstrap/js/device.min.js"></script>
    <script src="View/bootstrap/js/slider.js"></script>
    <script src="View/bootstrap/js/bootstrap.min.js"></script>
    <script src="View/bootstrap/js/myjs.js"></script>
</body>
</html>